### ISSUE TITLE
Cantamen based feeds unexpectedly large

### ISSUE THREAD

**Issue by hbruch** [mobidata-bw/x2gbfs#63]
Cantamen based feeds currently fail due to timeout exceptions and large response message sizes (probably as they have been extended with booking url information, which is very verbose):

```
ERROR:x2gbfs:Generating feed for my-e-car failed!
Traceback (most recent call last):
  File "/app/x2gbfs/x2gbfs.py", line 61, in main
    generate_feed_for(provider, output_dir, base_url)
  File "/app/x2gbfs/x2gbfs.py", line 80, in generate_feed_for
    (info, status, vehicle_types, vehicles, last_reported) = transformer.load_stations_and_vehicles(extractor)
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ...
  File "/app/x2gbfs/providers/api/ixsi.py", line 23, in _request
    return websocket.recv(timeout=self.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/sync/connection.py", line 201, in recv
    raise self.protocol.close_exc from self.recv_events_exc
websockets.exceptions.ConnectionClosedError: sent 1009 (message too big) over size limit (3048899 > 1048576 bytes); no close frame received
```

```
ERROR:x2gbfs:Generating feed for stadtmobil_suedbaden failed!
Traceback (most recent call last):
  File "/app/x2gbfs/x2gbfs.py", line 61, in main
    generate_feed_for(provider, output_dir, base_url)
 ...
  File "/app/x2gbfs/providers/api/ixsi.py", line 23, in _request
    return websocket.recv(timeout=self.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/sync/connection.py", line 199, in recv
    return self.recv_messages.get(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/sync/messages.py", line 98, in get
    raise TimeoutError(f"timed out in {timeout:.1f}s")
TimeoutError: timed out in 5.0s
```

While accepted timeouts already can be configured via `CANTAMEN_IXSI_API_TIMEOUT`(default currently is 5 seconds), this is not the case for the max message size, wich defaults to `2**20`.

The expected message_size should be configurable and have a larger default.

**Comment by hbruch** [comment]
The root cause of this exception is that Cantamen responds with all attributes defined for any accessible provider, even though only a single provider is requested per `ProviderFilter`. I.e., a  `ProviderFilter` is not applied to it's attributes. As a couple of providers have become accessible recently, their attributes (i.e. urls) sum up to a huge size increase of the response message.

Thus, I classify this as a data issue which should be solved by Cantamen. Nevertheless, as a temporary workaround, we provided #64, which allows configuration of max message size and increases the default timeout.

**Comment by ThorstenFroehlinghaus** [comment]
My last IXSI Request 2 weeks ago for 10 providers had a size of 6743 KB, my IXSI Request today has a size of 7036 KB. If I request two providers I still get all attributes. I informed Cantamen already last month about this data issue. However, it is difficult to convince Cantamen that they really have a data issue. I will try again.

**Comment by ThorstenFroehlinghaus** [comment]
Cantamen today confirmed, that my new  data issue is the same data issue as last month. They are still analysing it.

**Comment by ThorstenFroehlinghaus** [comment]
Cantamen answered:
_die Schnittstelle ist ausschließlich zur Datenlieferung da. Hier können keine Filter oder Ähnliches verwendet werden, wenn Sie nicht von sich aus die Suche auf den Anbieter einschränken.
Die IDs der Attribute sollten aber eindeutig sein, sodass sie diese in der weiteren Verarbeitung filtern können. Haben Sie danach geschaut?_
It seems as if they are not willing to filter the attributes of non-requested providers. Instead, they expect us to do this.
Can we live with this data issue? We must expect the attribute set to grow if new providers are activated.

**Comment by hbruch** [comment]
I'm not happy about this. It will catch us sooner or later again. And what is really annoying, is that most of the data is for totally redundant information (deeplinks). 

If Cantamen want's to be able to change deeplink patterns, a better approach IMHO would be to define a single (or per provider) deeplink template pattern like `https://ewi3.cantamen.de/?openPlace=${placeId}` or `https://ewi3.cantamen.de/?openBookee=${bookeeId}`, which then can be referenced by the entities.

**Comment by ThorstenFroehlinghaus** [comment]
I agree, but Cantamen told us that we should not use deeplink patterns. Instead, we shall rely on the deeplink attributes. Unfortunately, Cantamen shows no interest in improving their output format.

**Comment by ThorstenFroehlinghaus** [comment]
Meanwhile, Cantamen reduced the size of their response messages and avoids attributes which do not belong to the requested provider.
